// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptkdbfatsnhtbwnzwwqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0a2RiZmF0c25odGJ3bnp3d3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjcxODcsImV4cCI6MjA2MjMwMzE4N30.gd9I9BaMI1qGDY9l69JJe7WlLDt6B3sXSqUsEsYotY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);